apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: nephio-system/openshift-packages-main
  name: openshift-packages-main
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /
    repo: https://github.com/aprincipRedhat/blueprints-nephio-openshift.git
  type: git