apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: example-repo
  namespace: default
spec:
  content: Package
  deployment: true
  git:
    branch: main
    directory: /
    repo: http://gitea.gitea.svc.cluster.local:3000/gitea/example-repo.git
    secretRef:
      name: example-repo-access-token-porch
  type: git
