kind: SecurityContextConstraints
metadata: # kpt-merge: /gitea
  name: gitea
  annotations:
    internal.kpt.dev/upstream-identifier: 'security.openshift.io|SecurityContextConstraints|default|gitea'
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: gitea/gitea-role
  name: gitea-role
  namespace: gitea
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|gitea|gitea-role'
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - gitea
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: gitea/gitea-rolebinding
  name: gitea-rolebinding
  namespace: gitea
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|gitea|gitea-rolebinding'
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: gitea-role
  apiGroup: rbac.authorization.k8s.io
