config:
  repoURL: https://github.com/openshift-telco/blueprints-nephio-openshift.git

blueprints:
  00-argocd-kpt-config:
    enabled: true
  01-gitea:
    enabled: true
  02-configsync:
    enabled: true
  03-porch:
    enabled: true
  04-network-config:
    enabled: true
  05-resource-backend:
    enabled: true
  06-nephio-controllers:
    enabled: true
  07-stock-repos:
    enabled: true
  08-nephio-webui:
    enabled: true
  09-mgnt-config:
    enabled: true