apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /kptfile.kpt.dev
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|kptfile.kpt.dev'
data:
  oauth-redirect: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"nephio"}}'
  mountPath: /tmp/fakepath
  secretName: nephio-tls
  defaultMode: 420
  name: example
