apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nephio-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nephio-mgnt/helm
    repoURL: https://gitlab.consulting.redhat.com/telus-nephio/nephio-v1-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true