apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-configsync # kpt-set: ${cluster-name}-configsync
  namespace: example
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: configsync
    repo: nephio-example-packages
    revision: v1
  downstream:
    package: example-configsync # kpt-set: ${cluster-name}-configsync
    repo: management  # kpt-set: ${cluster-name}
  injectors:
  - kind: WorkloadCluster
    name: example # kpt-set: ${cluster-name}
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example