apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: example # kpt-set: ${cluster-name}
  namespace: example # kpt-set: ${cluster-name}
spec:
  clusterName: example # kpt-set: ${cluster-name}
  clusterNamespace: example # kpt-set: ${cluster-name}
  clusterLabels:
    cloud: auto-detect
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true