apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: "ca-montreal" # kpt-set: ${cluster-name}
data:
  .dockerconfigjson: "" # kpt-set: ${pull-secret}
type: kubernetes.io/dockerconfigjson
