apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
  name: catalog-infra-capi
  namespace: default
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /infra/capi
    repo: https://github.com/nephio-project/catalog.git
  type: git
