apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: nephio-webui/nephio-webui
  name: nephio-webui
  namespace: nephio-webui
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|nephio-webui|nephio-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nephio-webui
  template:
    metadata:
      labels:
        app: nephio-webui
    spec:
      serviceAccountName: nephio-webui-sa
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: nephio/kpt-backstage-plugins:v1.0.1
        imagePullPolicy: IfNotPresent
        args:
        - --config
        - /etc/config/app-config.nephio.yaml
        ports:
        - name: http
          containerPort: 7007
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: nephio-tls
          mountPath: /tmp/fakepath
        readinessProbe:
          httpGet:
            path: /
            port: 7007
      - args:
        - -provider=openshift
        - -https-address=:8443
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:7007
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -cookie-secret="KVgwiyRNt_deA_shUsVgoQ=="
        - -openshift-service-account=nephio-webui-sa
        - -skip-auth-regex=^/metrics
        - -skip-provider-button
        - -request-logging=true
        image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12
        imagePullPolicy: IfNotPresent
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - MKNOD
        volumeMounts:
        - mountPath: /etc/tls/private
          name: nephio-tls
      volumes:
      - name: config-volume
        configMap:
          name: nephio-webui-config
      - name: nephio-tls
        secret:
          secretName: nephio-tls
          defaultMode: 420
