apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  oauth-redirect: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"nephio"}}'
  mountPath: /tmp/fakepath
  secretName: nephio-tls
  defaultMode: 420
