kind: Service
apiVersion: v1
metadata:
  name: proxy
  namespace: nephio-webui
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: nephio-tls
    internal.kpt.dev/upstream-identifier: '|Service|nephio-webui|proxy'
spec:
  ports:
    - name: proxy
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
  selector:
    app: nephio-webui
